meta/conf/bitbake.conf: let users modify (some) DEPLOY_DIRs
Allow users build for multiple machines in a loop with clean tmp without
loosing required artifacts and avoid errors like following when cleaning
not entire tmp/:

    ERROR: foobar-git-r0 do_deploy_setscene: The recipe foobar is trying to install files into a shared area when those files already exist. Those files and their manifest location are:

Signed-off-by: Jens Rehsack <sno@netbsd.org>